# Render Blueprint for AttendEase Backend
# This file can be used to deploy your entire stack with one click

services:
  - type: web
    name: attendease-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: attendease-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: attendease-db
    databaseName: attendease
    user: attendease_user
